#!/bin/zsh
#Script Settings
shell="zsh"
declare github-respositories[4]=(mgattozzi.github.io, awesome-config, dotfiles, Scripts)
declare bitbucket-repositories[3]=()
#Functions
function github(){
	if [ cd ~/ ] then;
		mkdir Github && cd Github
		for i in "${github-repositories[@]}"
		do
			git clone git@github.com:mgattozzi/$i.git
		done
		cd Scripts/Arch\ Linux\ Scripts
		sh yaourt #Install yaourt
		sudo sign-key 5EE46C4C #Sign repo-ck key
	fi
}
#Setup all needed programs
sudo pacman -S multilib-devel git zsh libreoffice xorg-server xorg-xbacklight steam ruby wget curl ttf-inconsolata rxvt-unicode vim
#Home Directory
github

#Install install AUR programs
yaourt -S spotify

#Install configuration files

#Install linux-ck and blackarch repository
curl -s http://blackarch.org/strap.sh | sudo sh
sudo pacman -S blackarch linux-ck-ivybridge
sudo pacman -Syu

#Remove unwanted files/programs
