#!/bin/zsh
# Script Settings
user="michael"
github-respositories=(mgattozzi.github.io awesome-config dotfiles Scripts)
bitbucket-repositories=(homework config-files)
aurprograms=(spotify mopidy-spotify pia-tools)
unwantedprograms=(bash nano)
#Functions
function github(){
	#Sets up Github Repositories and sets them up for their intended usage
	#Initialize Repositories
	cd /home/$user		
	mkdir Github && cd Github
	for i in "${github-repositories[@]}"
	do
		git clone git@github.com:mgattozzi/$i.git
	done
	#Installs aura and signs repo-ck key
	cd /home/$user/Github/Scripts/Arch\ Linux\ Scripts
	./aura
	sudo sign-key 5EE46C4C
	#Setup Dotfiles
	cd /home/$user/Github/dotfiles
	./link
	#Setup Awesome
	if [ "pacman -Q awesome" ]; then
		cd /home/$user/.config
		rm -rf awesome
		ln -s /home/$user/Github/awesome-config awesome
	else
		cd /home/$user
		if [ "ls -a | grep .config" ]; then 
			ln -s /home/$user/Github/awesome-config .config/awesome
		else
			mkdir .config
			ln -s /home/$user/Github/awesome-config awesome
		fi
	fi
}

function bitbucket(){
	#Create repositories
	cd /home/$user
	mkdir Bitbucket && cd Bitbucket
	for i in "${bitbucket-repositories[@]}"
	do
		git clone git@bitbucket.org:mgattozzi/$i.git
	done

	#Gene Guru
	git clone git@bitbucket.org:gene-guru/geneguru_site.git

	#Setup Config Files
	cd /home/$user/Bitbucket/config-files
	sudo ./link

}
#Script Start

#Checking for Script Dependencies
if [ "pacman -Q sudo zsh git ssh" != true ]; then
	echo "Installing needed programs. Please insert root password"
	su -c "pacman -S sudo zsh git"
	echo "Place yourself in the sudoers file"
	su -c "visudo"
	echo "Please install ssh keys for repositories. The script will abort now"
	exit 1
fi

#Github and Bitbucket setup
github
bitbucket

#Install Blackarch repository
curl -s http://blackarch.org/strap.sh | sudo sh

#Install all needed programs
cd /home/$user/Github/Scripts/Arch\ Linux\ Scripts\
echo "Installing packages please wait"
sudo aura -S $(cat packages) 
sudo aura -Aa $aurprograms

#Remove unwanted files/programs
sudo aura -Rns $unwantedprograms

#Regen grub config
grub-mkconfig -o /boot/grub/grub.cfg

#Systemctl Commands
sudo systemctl enable pia-tools@Switzerland.service
sudo systemctl enable preload
sudo systemctl enable mopidy
sudo touch /etc/iptables/iptables.rules
sudo systemctl enable iptables
sudo systemctl enable cronie
